export const api_key = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;

export const categories = [
  { id: 1, value: "DROIT ADMINISTRATIF" },
  { id: 2, value: "DROIT AFFAIRES" },
  { id: 3, value: "DROIT BANCAIRE" },
  { id: 4, value: "DROIT CIVIL" },
  { id: 5, value: "DROIT COMMERCIAL" },
  { id: 6, value: "DROIT DE FUSIONS ET ACQUISITIONS" },
  { id: 7, value: "DROIT DE L'ENVIRONNEMENT" },
  { id: 8, value: "DROIT DE L'IMMIGRATION" },
  { id: 9, value: "DROIT DE L'IMMOBILIER" },
  { id: 10, value: "DROIT DE LA CONSOMMATION" },
  { id: 11, value: "DROIT DE LA PRESSE" },
  { id: 12, value: "DROIT DE LA PROPRIÉTÉ INTELLECTUELLE" },
  { id: 13, value: "DROIT DE LA SANTÉ" },
  { id: 14, value: "DROIT DES ASSURANCES" },
  { id: 15, value: "DROIT DES CONTRATS" },
  { id: 16, value: "DROIT DES ÉNERGIES" },
  { id: 17, value: "DROIT DES ENTREPRISES" },
  { id: 18, value: "DROIT DES ÉTRANGERS" },
  { id: 19, value: "DROIT DES FUSIONS ET ACQUISITIONS" },
  { id: 20, value: "DROIT DES INVESTISSEMENTS" },
  { id: 21, value: "DROIT DES PRIVATISATIONS" },
  { id: 22, value: "DROIT DES RECOUVREMENT DE CRÉANCES" },
  { id: 23, value: "DROIT DES SOCIÉTÉS" },
  { id: 24, value: "DROIT DES TELECOM/TIC" },
  { id: 25, value: "DROIT DES TRANSPORTS" },
  { id: 26, value: "DROIT DOUANIER" },
  { id: 27, value: "DROIT DU SPORT" },
  { id: 28, value: "DROIT DU TRAVAIL" },
  { id: 29, value: "DROIT FAMILIAL" },
  { id: 30, value: "DROIT FONCIER" },
  { id: 31, value: "DROIT INTERNATIONAL PRIVÉ" },
  { id: 32, value: "DROIT JUDICIAIRE" },
  { id: 33, value: "DROIT MARITIME" },
  { id: 34, value: "DROIT PÉNAL" },
  { id: 35, value: "DROIT ROUTIER" },
  { id: 36, value: "DROIT SOCIAL" },
  { id: 37, value: "DROITS DE L'HOMME" },
];
